name: 🐛 Bug Report
description: Report a bug or issue with the Saved Reddit Exporter plugin
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight Checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of the plugin
          required: true
        - label: I have tried restarting Obsidian
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
    validations:
      required: true

  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian Version
      description: What version of Obsidian are you running?
      placeholder: "e.g., 1.4.16"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of Saved Reddit Exporter are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: Any relevant console logs (open DevTools with Ctrl+Shift+I)
      placeholder: Paste console errors here...
      render: text

  - type: textarea
    id: reddit-setup
    attributes:
      label: Reddit Configuration
      description: Details about your Reddit app setup (don't include secrets!)
      placeholder: |
        - Reddit app type: script/web app
        - Redirect URI configured: http://localhost:9638
        - Permissions granted: read, history, identity
        - Any custom port settings?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or details about the problem
      placeholder: Screenshots, related issues, etc...