name: ❓ Question / Help
description: Ask a question or get help with the Saved Reddit Exporter plugin
title: "[Question]: "
labels: ["question", "help-wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about the plugin? Need help getting it set up? Ask away!

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight Checklist
      description: Please verify these before submitting
      options:
        - label: I have read the README.md and DEVELOPMENT.md documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What kind of help do you need?
      options:
        - Installation / Setup
        - Configuration
        - Reddit API setup
        - Usage / How-to
        - Troubleshooting
        - Development / Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I'm trying to... but I can't figure out how to...
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
      placeholder: |
        I tried...
        I looked at...
        I searched for...

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS

  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian Version
      placeholder: "e.g., 1.4.16"

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      placeholder: "e.g., 1.0.0"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other details that might be helpful
      placeholder: Screenshots, error messages, configuration details, etc...